version: "2"
plugins:
  eslint:
    enabled: false
checks:
  method-lines:
    config:
      threshold: 35
  similar-code:
    config:
      threshold: 70
  identical-code:
    config:
      threshold: 70
exclude_patterns:
  - "**/node_modules/"
  - "**/test/"
  - "**/__tests__/"
  - "**/tests/"
  - "**/UI/"
 